apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-voice.fullname" . }}
  labels:
    {{- include "test-voice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-voice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "test-voice.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.image.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
