apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "test-voice.fullname" .) }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "test-voice.selectorLabels" . | nindent 4 }}
